sudo: required

addons:
  ssh_known_hosts:
    - demo.swellrt.org
    - assange.fdi.ucm.es

language: java
jdk: oraclejdk8


branches:
  only:
    - master
    - alpha-develop
    - /v[0-9]+\.[0-9]+\.[0-9]+-alpha/

services:
  - docker

script:
  - ./gradlew clean jar compileJsWebDev test createDistBin

after_success:
  - .travis/deploy.sh
